# Generated by Django 3.0.5 on 2020-04-29 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worktile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='sontask',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止时间'),
        ),
    ]
