# Generated by Django 3.0.5 on 2020-04-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktile', '0002_auto_20200429_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': '日程', 'verbose_name_plural': '日程'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '通讯录', 'verbose_name_plural': '通讯录'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
        migrations.AlterModelOptions(
            name='sontask',
            options={'verbose_name': '子任务信息', 'verbose_name_plural': '子任务信息'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务信息', 'verbose_name_plural': '任务信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
