# Generated by Django 3.0.5 on 2020-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktile', '0004_auto_20200429_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(null=True, to='worktile.User', verbose_name='对应用户'),
        ),
    ]
