# Generated by Django 3.0.5 on 2020-04-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktile', '0007_auto_20200430_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sontask',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sontask_manager', to='worktile.User', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='worktile.User', verbose_name='负责人'),
        ),
    ]
