# Generated by Django 3.0.5 on 2020-05-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktile', '0009_auto_20200518_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to='worktile.User', verbose_name='项目创建者'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=20, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='constellation',
            field=models.CharField(max_length=20, null=True, verbose_name='星座'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=5, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(max_length=500, null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=50, null=True, verbose_name='职业'),
        ),
    ]
